-- MySQL Script generated by MySQL Workbench
-- 11/25/16 11:28:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema best_places
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema best_places
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `best_places` DEFAULT CHARACTER SET utf8 ;
USE `best_places` ;

-- -----------------------------------------------------
-- Table `best_places`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `best_places`.`User` ;

CREATE TABLE IF NOT EXISTS `best_places`.`User` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` CHAR(128) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `hometown` VARCHAR(45) NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_places`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `best_places`.`Place` ;

CREATE TABLE IF NOT EXISTS `best_places`.`Place` (
  `placeId` VARCHAR(28) NOT NULL,
  `additionalInformation` JSON NULL,
  PRIMARY KEY (`placeId`),
  UNIQUE INDEX `placeId_UNIQUE` (`placeId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_places`.`UserPlaceInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `best_places`.`UserPlaceInformation` ;

CREATE TABLE IF NOT EXISTS `best_places`.`UserPlaceInformation` (
  `user` VARCHAR(45) NOT NULL,
  `place` VARCHAR(28) NOT NULL,
  `favorite` TINYINT(1) NULL DEFAULT 0,
  `reviewText` LONGTEXT NULL DEFAULT NULL,
  `stars` INT NULL,
  `reviewShowName` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user`, `place`),
  INDEX `place_idx` (`place` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `best_places`.`User` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `place`
    FOREIGN KEY (`place`)
    REFERENCES `best_places`.`Place` (`placeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_places`.`Visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `best_places`.`Visit` ;

CREATE TABLE IF NOT EXISTS `best_places`.`Visit` (
  `visitId` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `place` VARCHAR(28) NOT NULL,
  `vistime` DATETIME NOT NULL DEFAULT NOW(),
  `notes` LONGTEXT NULL DEFAULT '',
  `money` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`visitId`),
  INDEX `place_idx` (`place` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `best_places`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `place`
    FOREIGN KEY (`place`)
    REFERENCES `best_places`.`Place` (`placeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
